name: CI/CD to Kubernetes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner | lower }}/foodapp/php-apache # Perhatikan 'foodapp' menggunakan huruf kecil

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 # Updated to v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 # Updated to v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4 # Updated to v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        provenance: false # Added to address potential warning
    
    - name: Set up kubectl
      uses: azure/k8s-set-context@v3 # Updated to v3
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    
    - name: Deploy to Kubernetes
      run: |
        # Update image in deployment
        kubectl set image deployment/php-apache php-apache=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        # Verify deployment
        kubectl rollout status deployment/php-apache
